import serial
import time
import re
import threading

class OumanEH203:
    """
    Ouman EH-203 interface using its SMS command protocol.

    Ubuntu emulates a GSM modem on the EH-203 serial port.
    Initial implementation is read-only.
    """

    BAUDRATE = 9600

    def __init__(self, port):
        self.port = port
        self.serial = None
        self.initialized = False

    def open(self):
        self.serial = serial.Serial(
            self.port,
            self.BAUDRATE,
            bytesize=8,
            parity=serial.PARITY_NONE,
            stopbits=1,
            timeout=0.1,
            xonxoff=False,
            rtscts=False,
            dsrdtr=False,
        )

    def close(self):
        if self.serial:
            self.serial.close()
            self.serial = None

    def _write(self, data):
        self.serial.write(data)
        self.serial.flush()

    def _modem_reply(self, command):
        """
        Emulate the subset of MC55i AT commands used by EH-203.
        """

        if command == b"AT\r":
            return b"\r\nOK\r\n"

        if command == b"AT+CPIN?\r":
            return b"\r\n+CPIN: READY\r\n\r\nOK\r\n"

        if command == b'ATE0+CSCS="GSM"\r':
            return b"\r\nOK\r\n"

        if command == b"AT+CSMS=1\r":
            return b"\r\n+CSMS: 1,1,1\r\n\r\nOK\r\n"

        if command == b"AT+CNMI=2,2\r":
            return b"\r\nOK\r\n"

        if command == b"AT+CMGF=1\r":
            self.initialized = True
            return b"\r\nOK\r\n"

        if command == b"AT+CNMA\r":
            return b"\r\nOK\r\n"

        if command.startswith(b"AT+CSCA="):
            return b"\r\nOK\r\n"

        if command.startswith(b"AT+CMGS="):
            return b"\r\n> "

        return None

    def wait_for_initialization(self, timeout=30):
        """
        Wait for EH-203 to initialize the emulated modem.
        """

        end = time.time() + timeout
        buf = b""

        while time.time() < end:
            data = self.serial.read(256)

            if not data:
                continue

            buf += data

            while b"\r" in buf:
                line, buf = buf.split(b"\r", 1)
                command = line + b"\r"

                if command == b"\x1a\r":
                    continue

                reply = self._modem_reply(command)

                if reply:
                    self._write(reply)

                if self.initialized:
                    return True

        return False

    def _send_fake_sms(self, text):
        """
        Deliver an SMS command to EH-203 through the emulated modem.

        The sender number is intentionally fictitious. EH-203 will direct
        its reply to this number, but the reply remains on the local serial
        connection.
        """

        sms = (
            b'\r\n+CMT: "+358400000000",,"26/09/28,12:50:00+12"\r\n'
            + text.encode("ascii")
            + b"\r\n"
        )

        self._write(sms)

    def _receive_sms_replies(self, timeout=30):
        """
        Receive one or more SMS replies generated by EH-203.
        """

        end = time.time() + timeout

        command_buf = b""
        sms_buf = b""
        messages = []

        receiving_sms = False
        last_message_time = None

        while time.time() < end:

            # Once at least one message has arrived, allow a short period
            # for continuation messages.
            if messages and last_message_time:
                if time.time() - last_message_time > 3:
                    break

            data = self.serial.read(256)

            if not data:
                continue

            if receiving_sms:
                sms_buf += data

                if b"\x1a" in sms_buf:
                    body, rest = sms_buf.split(b"\x1a", 1)

                    messages.append(body)
                    last_message_time = time.time()

                    self._write(
                        b"\r\n+CMGS: 1\r\n\r\nOK\r\n"
                    )

                    receiving_sms = False
                    sms_buf = b""

                    if rest:
                        command_buf += rest

                continue

            command_buf += data

            while b"\r" in command_buf:
                line, command_buf = command_buf.split(b"\r", 1)
                command = line + b"\r"

                if command == b"\x1a\r":
                    continue

                reply = self._modem_reply(command)

                if command.startswith(b"AT+CMGS="):
                    if reply:
                        self._write(reply)

                    receiving_sms = True

                    # Anything already buffered after CMGS belongs
                    # potentially to the SMS body.
                    if command_buf:
                        sms_buf += command_buf
                        command_buf = b""

                    break

                if reply:
                    self._write(reply)

        return messages

    @staticmethod
    def _decode_ouman(data):
        """
        Convert the character substitutions observed from EH-203
        to readable Finnish text.

        Keep this deliberately small until more characters have been
        observed from the real controller.
        """

        text = data.decode("ascii", errors="replace")

        # Observed Ouman/GSM character substitutions.
        text = text.replace("{", "ä")
        text = text.replace("|", "ö")

        return text

    @staticmethod
    def _combine_messages(messages):
        parts = []

        for message in messages:
            text = OumanEH203._decode_ouman(message)

            # Remove repeated heading from continuation SMS.
            text = re.sub(
                r"^MITTAUKSET:\s*",
                "",
                text,
                flags=re.IGNORECASE,
            )

            text = text.replace("...jatkuu...", "")
            parts.append(text.strip())

        text = " / ".join(parts)

        # Clean up separators created at SMS continuation boundaries.
        text = re.sub(r"/\s*/", "/", text)

        return text

    @staticmethod
    def _parse_measurements(text):
        """
        Parse the known EH-203 MITTAUKSET response.

        Values are kept exactly as reported by EH-203.
        """

        mapping = {
            "L1 Menovesi": "l1_supply",
            "L1 Huone": "l1_room",
            "L1 Paluuvesi": "l1_return",
            "Ulkolämpö": "outdoor",
            "L2 Menovesi": "l2_supply",
            "L2 Huone": "l2_room",
            "L2 Paluuvesi": "l2_return",
            "LV Menovesi": "dhw_supply",
            "LV kierto/en": "dhw_circulation",
            "Varaajan läm": "tank",
            "Sadevesi Pum": "rainwater_pump",
        }

        result = {}

        # Search known field names directly instead of splitting on "/".
        # One EH-203 field ("LV kierto/en") contains "/" in its name.
        for ouman_name, key in mapping.items():
            pattern = re.escape(ouman_name) + r"\s*=\s*(-?\d+(?:\.\d+)?)"
            match = re.search(pattern, text, flags=re.IGNORECASE)

            if not match:
                continue

            value = match.group(1)

            try:
                result[key] = float(value)
            except ValueError:
                result[key] = value

        return result

    def get_measurements(self):
        """
        Request MITTAUKSET from EH-203 and return parsed values.

        EH-203 accepts an incoming +CMT SMS also when the emulated
        modem has not been initialized during this process lifetime.
        """

        if not self.serial:
            self.open()

        self._send_fake_sms("Mittaukset")

        messages = self._receive_sms_replies()

        if not messages:
            raise TimeoutError(
                "No MITTAUKSET response received from EH-203"
            )

        text = self._combine_messages(messages)
        values = self._parse_measurements(text)

        return {
            "text": text,
            "measurements": values,
        }

class OumanEH203Service:
    """
    Background service for Ouman EH-203.

    Keeps the latest successful MITTAUKSET response in memory.
    Failures never block or stop the rest of SMA Local Portal.
    """

    def __init__(self, port, poll_interval=60):
        self.port = port
        self.poll_interval = poll_interval

        self.lock = threading.Lock()

        self.status = {
            "available": False,
            "measurements": {},
            "text": None,
            "updated_at": None,
            "error": None,
        }

        self.thread = None
        self.running = False

    def start(self):
        if self.thread and self.thread.is_alive():
            return

        self.running = True

        self.thread = threading.Thread(
            target=self._run,
            daemon=True,
            name="OumanEH203Service",
        )

        self.thread.start()

    def get_status(self):
        with self.lock:
            return dict(self.status)

    def _update_status(
        self,
        available,
        measurements=None,
        text=None,
        error=None,
    ):
        with self.lock:
            self.status["available"] = available
            self.status["error"] = error

            if measurements is not None:
                self.status["measurements"] = measurements

            if text is not None:
                self.status["text"] = text

            if available:
                self.status["updated_at"] = time.strftime(
                    "%Y-%m-%dT%H:%M:%S"
                )

    def _run(self):
        while self.running:
            ouman = None

            try:
                print(
                    f"Ouman EH-203: opening {self.port}"
                )

                ouman = OumanEH203(self.port)
                ouman.open()


                while self.running:
                    try:
                        result = ouman.get_measurements()

                        self._update_status(
                            available=True,
                            measurements=result["measurements"],
                            text=result["text"],
                            error=None,
                        )

                        print(
                            "Ouman EH-203: measurements updated"
                        )

                    except Exception as exc:
                        print(
                            f"Ouman EH-203 measurement error: {exc}"
                        )

                        self._update_status(
                            available=False,
                            error=str(exc),
                        )

                        # Re-open and reinitialize the serial
                        # connection on the next outer-loop pass.
                        break

                    # Sleep in small pieces so shutdown/restart
                    # remains responsive.
                    end = time.time() + self.poll_interval

                    while (
                        self.running
                        and time.time() < end
                    ):
                        time.sleep(1)

            except Exception as exc:
                print(
                    f"Ouman EH-203 service error: {exc}"
                )

                self._update_status(
                    available=False,
                    error=str(exc),
                )

            finally:
                if ouman:
                    try:
                        ouman.close()
                    except Exception:
                        pass

            if self.running:
                time.sleep(10)
